all : min_max_sum rotate_integer

min_max_sum : min_max_sum.o
	g++ -o min_max_sum min_max_sum.o

rotate_integer : rotate_integer.o
	g++ -o rotate_integer rotate_integer.o

clean :
	rm *.o
	rm min_max_sum
	rm rotate_integer
