all : exceptions_1 exceptions_2 exceptions_3 exceptions_3_2 exceptions_4 
exceptions_1 : exceptions_1.o
	g++ -o exceptions_1 exceptions_1.o 

exceptions_2 : exceptions_2.o 
	g++ -o exceptions_2 exceptions_2.o 

exceptions_3 : exceptions_3.o 
	g++ -o exceptions_3 exceptions_3.o

exceptions_3_2 : exceptions_3_2.o
	g++ -o exceptions_3_2 exceptions_3_2.o

exceptions_4 : exceptions_4.o 
	g++ -o exceptions_4 exceptions_4.o 
clean : 
	rm *.o
